### PR TITLE
Hardfork

### PR DESCRIPTION
**Pull request by davidmurdoch**
This PR (to `master`) updates Ganache v1 to `ganache-core@2.4.0`, adds a new HARDFORK setting, and sets the default `hardfork` option to `constantinople`.

### Adds HARDFORK to status menu:
image

### Adds HARDFORK `select` list to SETTINGS menu:
image

---

This PR is intended to be followed by a minor version release: Ganache v1.3.0.

### CODE REVIEW

**Comment by adrianmcli** [comment]
The code looks good to me, will take a look to see if it loads properly.

**Comment by honestbonsai** [comment]
Code LGTM.

Tested on both forks. Ran some contract creation tx and seems to work.

Only comment from me is the style of the dropdown is quite different from the current Ganache ui style. Could always address in a separate issue PR.

**Comment by adrianmcli** [comment]
For reference, this is example usage of the `StyledSelect` component:

https://github.com/trufflesuite/ganache/blob/aeaac841d0fff53d0f7429859d68f6bee501675c/src/renderer/screens/config/ConfigScreens/ServerScreen.js#L4

**Comment by davidmurdoch** [comment]
> For reference, this is example usage of the `StyledSelect` component:
> 
> [ganache/src/renderer/screens/config/ConfigScreens/ServerScreen.js](https://github.com/trufflesuite/ganache/blob/aeaac841d0fff53d0f7429859d68f6bee501675c/src/renderer/screens/config/ConfigScreens/ServerScreen.js#L4)
> 
> Line 4 in [aeaac84](/trufflesuite/ganache/commit/aeaac841d0fff53d0f7429859d68f6bee501675c)
> 
>  import StyledSelect from "../../../components/styled-select/StyledSelect";

Fixed!

image

**Comment by adrianmcli** [comment]
looks great, thanks @davidmurdoch!

**Pull request merged**
