### PR TITLE
Add account/address name (and rename) feature

### PR DESCRIPTION
**Pull request by zulhfreelancer**
This PR is for this [issue](https://github.com/trufflesuite/ganache/issues/334). I am not a ReactJS developer. In fact, never touch and do any ReactJS project before.

That means, some of my approach here might not be the best or following the 'best practices'. I also don't have any tests for this PR.

**Current build**

screen shot 2018-02-09 at 9 34 31 am

**Proposed build**

36016486-146f775c-0d6b-11e8-8256-53f7866a127d

**This PR build**

vlcsnap-2018-02-09-09h30m27s618

[ :movie_camera: Watch demo on YouTube](https://www.youtube.com/watch?v=q69kZ2DzMak&feature=youtu.be)

Would be great if this small PR can get merged. 🙂

### CODE REVIEW

**Comment by benjamincburns** [comment]
@seesemichaelj might want to consider this one during the truffle integration/workspaces work. Will probably need further design review from @DiscRiskandBisque.

**Comment by benjamincburns** [comment]
Hi @zulhfreelancer! Thanks for submitting this. We're going to add this feature at some point, but we need to put it through our usual design process. As a result we'll keep issue #334 open and use that to track the work for this.

**Comment by zulhfreelancer** [comment]
Noted @benjamincburns. Mind sharing the ETA? 🙂

**Comment by seesemichaelj** [comment]
@zulhfreelancer Unfortunately we don't really have an ETA, but hopefully before/around the beginning of October. We're pushing for a large release around then, and I'd hope we can fit this into it around then.

**Comment by zulhfreelancer** [comment]
@seesemichaelj awesome. We can launch it at TruffleCon. I'll be there. 🙂

**Pull request closed without merging**
