### PR TITLE
Support serving Ganache as web application instead of electron app

### PR DESCRIPTION
**Pull request by dylanseago**
Solution to issue https://github.com/trufflesuite/ganache/issues/129

This is a big PR because web support requires significant refactoring of electron specific dependencies in several locations as well as an entirely new backend server process.

Summary of changes:
- Refactor electron main process entry file into two `src/main/init.js` and `src/main/electron.js`
- Refactor environment dependent functions into `src/Kernel/app.js`
- Replace `universal-analytics` with `react-ga` because it doesn't work on the web
- Use `configstore` instead of `electron-settings` on the web
- Add express server for running on web (`src/main/web.js`)
- Use websockets for communication between backend and frontend in a way that replicates `ipcRenderer` and `ipcMain` (located in `src/wsActionClient.js` and `src/Kernel/actionClient.js`)
- Add new action `REQUEST_ACTION_HISTORY` to facilitate restoring state on the web
- Add new thunk `getLatestBlock` to retrieve the latest block on page load
- Compile both web and electron apps using webpack configs (located in `build` dir)
- Remove `electron-compile` as it's no longer needed
- Replace `.compilerc` with `.babelrc` since it was only needed for `electron-compile`
- Rename `src/index.js` to `src/app.js` so naming is consistent with `app.html` and `app.scss`
- Move `chain.js` into `src/main`

### CODE REVIEW

**Comment by benjamincburns** [comment]
@dylanseago - wow! This is amazing, and I'm so sorry for not connecting with you sooner!

Sadly, though you're trying to hit a moving target. Apart from the usual sort of merge conflicts, I think you've made some changes here which conflict with some fairly substantial changes I made to enable auto updates and the like. Furthermore it seems you're cleaning up some of our init logic (awesome!) but we've got a few in-progress changes in the pipeline for that as well.

Are you interested in continuing to work on this? If so, I can help guide you through the changes you'll need to make to get it merged. I'm happy to discuss that here, or we can set up a video call if you want to discuss more synchronously.

**Comment by benjamincburns** [comment]
Aside, I think it's worth pointing out that this change is somewhat of an emotional roller coaster for me as a maintainer. On the one hand it's awesome functionality that I'd really like to have. On the other, with changes this large there's bound to be substantial rework involved in getting it merged. If you're willing to do the rework there's no foul, but I feel terrible turning down a change like this due to architectural issues which could've been avoided had we been in better communication prior to the work getting started.

I'd encourage anyone considering a larger change like this to DM me on gitter, or even email me (ben.burns@consensys.net) so that we can coordinate that change.

**Comment by dylanseago** [comment]
@benjamincburns I was able to resolve the conflicts with minimal reworking. It turns out your auto update changes were quite well encapsulated and didn't cause any substantial barriers. I'll need you to confirm that auto update still works as expected. Everything else appears to be working on my end.

**Comment by benjamincburns** [comment]
Hi @dylanseago,

I'm really sorry to do this, but I'm afraid I need to close this one. The way we'd go about this feature would be to make the ganache UI capable of pointing at an arbitrary provider URL, and then users could run ganache-cli as a daemon (e.g. using our docker image) if they like. Otherwise we've discussed internally and for the moment at least we have no immediate plans on supporting a web-based Ganache UI.

**Comment by seesemichaelj** [comment]
@drandreaskrueger you can run Docker instances of [ganache-cli](https://github.com/trufflesuite/ganache-cli#docker) which you should be able to change the outside port number.

We're also working currently to support #684 (multiple instances of Ganache UI simultaneously)

**Pull request closed without merging**
