### PR TITLE
Feature/eslint prettier

### LINKED ISSUE #1080: Eslint and prettier for ganache-ui
We should have an eslint and prettier config to align styles between the team and contributors for ganache-ui.

### PR DESCRIPTION
**Pull request by honestbonsai**
Resolves #1080

### CODE REVIEW

**Comment by adrianmcli** [comment]
noice, lgtm

**Comment by adrianmcli** [comment]
@honestbonsai not sure why the PR build failed. Looks like an issue with the windows build? I'm inclined to just merge it anyway since the branch build was fine, but I'm not sure.

**Comment by seesemichaelj** [comment]
I believe that appveyor has issues building on the `pr` build. You need to investigate what the error is before "inclining to merge". The error was related to signing, and the other appveyor build was successful, which I would consider sufficient

**Comment by adrianmcli** [comment]
@seesemichaelj thanks for taking a look. I did investigate as I mentioned, but I couldn't make sense of all the windows noise.

**Comment by seesemichaelj** [comment]
>thanks for taking a look. I did investigate as I mentioned, but I couldn't make sense of all the windows noise.

@adrianmcli haha, I usually just read the first red line

>I don't know how windows builds work, but if the branch build was ok I don't see how this shouldn't be either. Why is this not deterministic?

I'm not sure actually. I didn't setup the build processes and didn't take the time to figure it out. I'm guessing some signing env variable is not set properly. If you look at the history of [appveyor.yml](https://github.com/trufflesuite/ganache/commits/develop/appveyor.yml) there was a [commit](https://github.com/trufflesuite/ganache/commit/29fd4de2fd75e8d203ef512d1be22d40670e4d30#diff-180360612c6b8c4ed830919bbb4dd459) about getting PR builds to get fixed from @benjamincburns. Perhaps the solution was there and got removed/changed over the last few months :man_shrugging:

**Comment by adrianmcli** [comment]
We really need a dedicated electron guy on this.

**Comment by honestbonsai** [comment]
Good to know about the keys and signing breaking PR builds.

**Pull request merged**
