### PR TITLE
Make code pretty

### PR DESCRIPTION
**Pull request by honestbonsai**
Does the auto formatting for #1085

More manual formatting to follow in a separate PR.

### CODE REVIEW

**Comment by adrianmcli** [comment]
Since this is the same AST, feel free to merge once builds check out.

**Comment by adrianmcli** [comment]
uh oh, @honestbonsai looks like conflicts were introduced by #1086

**Comment by honestbonsai** [comment]
@adrianmcli Will resolve. I'll just directly insert the files from #1086 to make it easy and clean up from there.

**Comment by honestbonsai** [comment]
Looks like the build is finally finished

**Pull request merged**
